import React, { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    brand: "Green Market Technology",
    slogan: "Un service de qualité pour une clientèle exceptionnelle",
    home: "Accueil",
    catalog: "Catalogue",
    cart: "Panier",
    orders: "Commandes",
    dashboard: "Tableau de bord",
    subscribe: "S'abonner",
    subscription: "Abonnement",
    login: "Se connecter",
    logout: "Déconnexion",
    search: "Rechercher...",
    add_to_cart: "Ajouter au panier",
    remove: "Retirer",
    checkout: "Passer la commande",
    total: "Total",
    quantity: "Quantité",
    price: "Prix",
    category: "Catégorie",
    all_categories: "Toutes les catégories",
    informatique: "Produits informatiques",
    services: "Services de secrétariat",
    jeux_video: "Consoles de jeux vidéo",
    televiseurs: "Téléviseurs",
    subscription_required: "Abonnement requis pour ajouter au panier",
    subscribe_now: "S'abonner maintenant",
    no_products: "Aucun produit trouvé",
    order_placed: "Commande passée avec succès",
    invoice: "Facture",
    print_invoice: "Imprimer la facture",
    export_pdf: "Exporter en PDF",
    status: "Statut",
    pending: "En attente",
    confirmed: "Confirmée",
    shipped: "Expédiée",
    delivered: "Livrée",
    cancelled: "Annulée",
    paid: "Payé",
    unpaid: "Non payé",
    date: "Date",
    actions: "Actions",
    view: "Voir",
    empty_cart: "Votre panier est vide",
    continue_shopping: "Continuer vos achats",
    active: "Actif",
    expired: "Expiré",
    plan: "Plan",
    basic: "Basique",
    premium: "Premium",
    enterprise: "Entreprise",
    per_month: "/ mois",
    features: "Fonctionnalités",
    choose_plan: "Choisir ce plan",
    current_plan: "Plan actuel",
    hero_title: "Votre partenaire technologique de confiance",
    hero_subtitle: "Découvrez notre sélection de produits informatiques, services professionnels et divertissement.",
    explore: "Explorer le catalogue",
    featured: "Produits en vedette",
    our_categories: "Nos catégories",
    subtotal: "Sous-total",
    items: "articles",
    stock: "En stock",
    out_of_stock: "Rupture de stock",
    manage_products: "Gérer les produits",
    manage_orders: "Gérer les commandes",
    manage_subscriptions: "Gérer les abonnements",
    revenue: "Revenus",
    total_orders: "Total commandes",
    total_products: "Total produits",
    active_subscribers: "Abonnés actifs",
    my_account: "Mon compte",
    product_details: "Détails du produit",
    back: "Retour",
    unit_price: "Prix unitaire",
    order_summary: "Résumé de la commande",
    order_number: "N° commande",
    payment_status: "Statut paiement",
    order_details: "Détails de la commande",
  },
  en: {
    brand: "Green Market Technology",
    slogan: "Quality service for exceptional customers",
    home: "Home",
    catalog: "Catalog",
    cart: "Cart",
    orders: "Orders",
    dashboard: "Dashboard",
    subscribe: "Subscribe",
    subscription: "Subscription",
    login: "Login",
    logout: "Logout",
    search: "Search...",
    add_to_cart: "Add to cart",
    remove: "Remove",
    checkout: "Checkout",
    total: "Total",
    quantity: "Quantity",
    price: "Price",
    category: "Category",
    all_categories: "All categories",
    informatique: "Computer Products",
    services: "Secretarial Services",
    jeux_video: "Video Game Consoles",
    televiseurs: "Televisions",
    subscription_required: "Subscription required to add to cart",
    subscribe_now: "Subscribe now",
    no_products: "No products found",
    order_placed: "Order placed successfully",
    invoice: "Invoice",
    print_invoice: "Print invoice",
    export_pdf: "Export PDF",
    status: "Status",
    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    paid: "Paid",
    unpaid: "Unpaid",
    date: "Date",
    actions: "Actions",
    view: "View",
    empty_cart: "Your cart is empty",
    continue_shopping: "Continue shopping",
    active: "Active",
    expired: "Expired",
    plan: "Plan",
    basic: "Basic",
    premium: "Premium",
    enterprise: "Enterprise",
    per_month: "/ month",
    features: "Features",
    choose_plan: "Choose this plan",
    current_plan: "Current plan",
    hero_title: "Your trusted technology partner",
    hero_subtitle: "Discover our selection of computer products, professional services and entertainment.",
    explore: "Explore catalog",
    featured: "Featured products",
    our_categories: "Our categories",
    subtotal: "Subtotal",
    items: "items",
    stock: "In stock",
    out_of_stock: "Out of stock",
    manage_products: "Manage products",
    manage_orders: "Manage orders",
    manage_subscriptions: "Manage subscriptions",
    revenue: "Revenue",
    total_orders: "Total orders",
    total_products: "Total products",
    active_subscribers: "Active subscribers",
    my_account: "My account",
    product_details: "Product details",
    back: "Back",
    unit_price: "Unit price",
    order_summary: "Order summary",
    order_number: "Order #",
    payment_status: "Payment status",
    order_details: "Order details",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = (key) => translations[lang]?.[key] || key;
  const toggleLang = () => setLang(prev => prev === 'fr' ? 'en' : 'fr');

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}